Numpy is written in C which are compiled and super fast. This is the main reason NumPy is up to 50x Faster than python list. It works with Arrays.

In [94]:
import sys

import numpy as np


When we were doing python we had the data structure **list** and **NumPy** is famous for **arrays**.

![np-array](course_screenshots/np-array.png "np-array")

### basic array creation

In [95]:
my_arr = np.array([1, 2, 3, 4, 5])
my_arr

array([1, 2, 3, 4, 5])

In [96]:
# numpy will hold only one datatype only, if we give mix data, it will convert all to same type

my_mix_list: list = [1, 2.5, "hello"]
my_mix_arr = np.array(my_mix_list)
my_mix_arr

array(['1', '2.5', 'hello'], dtype='<U32')

In [97]:
my_mix_list: list = [1, 2.5]
my_mix_arr = np.array(my_mix_list)
my_mix_arr  # converted everything in float

array([1. , 2.5])

In [98]:
# let's first see list and then array

my_list: list[int] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

print(sys.getsizeof(my_list))

my_array: np.ndarray = np.array(my_list)

print(sys.getsizeof(my_array))
my_array


136
192


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**list** is a **single** dimensional data structure, but Numpy array can be **multi-dimensional**.

In [99]:
# let' create multi-dimensional array

my_2d_arr = np.array([[1, 2, 3], [4, 5, 6]])
my_2d_arr  # it is 2 dimensions matrix

array([[1, 2, 3],
       [4, 5, 6]])

> 1. 1 dimension is called vector.
> 2. 2 dimension is called matrix.
> 3. above 2 dimensional are called Tensors.

### array generation function

In [100]:
arr_with_range: np.ndarray = np.arange(1, 11)
print(arr_with_range)  # single vector

arr_with_range_2d: np.ndarray = np.arange(1, 11).reshape(2, 5)
print(arr_with_range_2d)  # 2d matrix

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [101]:
# generate vector of zeros
zeros_arr: np.ndarray = np.zeros(10)
print(zeros_arr)
print(type(zeros_arr))

# generate vector of ones
ones_arr: np.ndarray = np.ones(10)
print(ones_arr)
print(type(ones_arr))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [102]:
# generate a matrix of zeros
zeros_2d_arr: np.ndarray = np.zeros((2, 3))
print(zeros_2d_arr)
print(type(zeros_2d_arr))

# generate a matrix of ones
ones_2d_arr: np.ndarray = np.ones((2, 3))
print(ones_2d_arr)
print(type(ones_2d_arr))

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>


In [103]:
# generate a linear space vector
linspace_arr: np.ndarray = np.linspace(1, 10, 20)
linspace_arr1: np.ndarray = np.linspace(0, 1, 100)
print(linspace_arr)  # space between numbers will be linear
print(type(linspace_arr))
print(linspace_arr1)  # space between numbers will always be linear

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
<class 'numpy.ndarray'>
[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.6565

#### random generation function

In [104]:
# create a random vector — generates random values between 0 and 1 (uniform distribution).
# NOTE: this is NOT normalization. Normalization is a deliberate transformation: (x - min) / (max - min).
# Standardization is also separate: (x - mean) / std → results in mean=0, std=1 (values are unbounded, not fixed to [-3, 3]).

random_arr: np.ndarray = np.random.rand(5)
random_arr  # vector of 5 values between 0 and 1

array([0.22215014, 0.32242111, 0.14753682, 0.03316558, 0.1057128 ])

In [105]:
np.random.randn(5)  # vector of 5 values between 3 and -3

array([-0.78771888, -1.37666816, -0.51454219, -0.24897324,  1.43540702])

In [106]:
# generate n numbers in array between 2 numbers
print(np.random.randint(1, 10, 5))  # 5 numbers between 1 and 9
print(np.random.randint(1, 10, (2, 3)))  # 2x3 matrix between 1 and 9

[2 1 9 3 6]
[[9 5 8]
 [3 4 7]]


### array attributes

In [108]:
arr: np.ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [109]:
arr.shape  # shape of the array


(3, 3)

In [110]:
arr.size  # number of elements in the array


9

In [111]:
arr.ndim  # number of dimensions in the array


2

In [112]:
arr.dtype  # data type of the array


dtype('int64')

In [113]:
arr.itemsize  # size of each element in the array


8

In [114]:
arr.nbytes  # total size of the array in bytes


72

### array methods

In [120]:
arr: np.ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### min and max

In [121]:
arr.min()  # minimum value in the array
arr.max()  # maximum value in the array
arr.min(axis=0)  # minimum value in each column
arr.min(axis=1)  # minimum value in each row
arr.max(axis=0)  # maximum value in each column
arr.max(axis=1)  # maximum value in each row


array([3, 6, 9])

#### sum

In [122]:
arr.sum()  # sum of all elements in the array
arr.sum(axis=0)  # sum of elements in each column
arr.sum(axis=1)  # sum of elements in each row


array([ 6, 15, 24])

#### mean

In [123]:
arr.mean()  # mean of all elements in the array
arr.mean(axis=0)  # mean of elements in each column
arr.mean(axis=1)  # mean of elements in each row


array([2., 5., 8.])

#### std

In [124]:
arr.std()  # standard deviation of all elements in the array
arr.std(axis=0)  # standard deviation of elements in each column
arr.std(axis=1)  # standard deviation of elements in each row


array([0.81649658, 0.81649658, 0.81649658])

#### var


In [125]:
arr.var()  # variance of all elements in the array
arr.var(axis=0)  # variance of elements in each column
arr.var(axis=1)  # variance of elements in each row


array([0.66666667, 0.66666667, 0.66666667])